name: Flutter APK Build

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # ✅ Latest version

      - name: Set up Flutter
        uses: subosito/flutter-action@v2  # ✅ Corrected
        with:
          flutter-version: '3.7.0'  # ✅ Specify the required version

      - name: Install dependencies
        run: flutter pub get  # ✅ Corrected syntax

      - name: Build APK
        run: flutter build apk --release  # ✅ Corrected syntax

      - name: Upload APK
        uses: actions/upload-artifact@v4  # ✅ Updated to v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
